export const POST_FUND_OTP_URL = '/v1/funds/otp'

export const POST_VERIFY_OTP_URL = '/v1/funds/otp/verify'

export enum OtpType {
  CANCEL_BUY_REQUEST = 'CANCEL_BUY_REQUEST',
  CANCEL_SELL_REQUEST = 'CANCEL_SELL_REQUEST',
  SUBMIT_SELL_REQUEST = 'SUBMIT_SELL_REQUEST',
  OFFICE_SUBMIT_SELL_REQUEST = 'OFFICE_SUBMIT_SELL_REQUEST',
  SUBMIT_BUY_REQUEST = 'SUBMIT_BUY_REQUEST',
  SUBMIT_BUY_POWER = 'SUBMIT_BUY_POWER',
  WEEKLY_ASSET = 'WEEKLY_ASSET',
  DAILY_ASSET = 'DAILY_ASSET',
  FINALIZATION_BUY_REQ = 'FINALIZATION_BUY_REQ',
  FINALIZATION_SELL_REQ = 'FINALIZATION_SELL_REQ',
  FINALIZATION_SUCCESS_BUY_REQ = 'FINALIZATION_SUCCESS_BUY_REQ',
  FINALIZATION_SUCCESS_SELL_REQ = 'FINALIZATION_SUCCESS_SELL_REQ',
  FINALIZATION_FAIL_BUY_REQ = 'FINALIZATION_FAIL_BUY_REQ',
  FINALIZATION_FAIL_SELL_REQ = 'FINALIZATION_FAIL_SELL_REQ',
  DAILY_BUY_POWER = 'DAILY_BUY_POWER',
  BROKER_AUTO_PAYMENT_FAILURE = 'BROKER_AUTO_PAYMENT_FAILURE',
  CHANGE_SURVEILLANT_BROKER_IN_PROGRESS = 'CHANGE_SURVEILLANT_BROKER_IN_PROGRESS',
  CHANGE_SURVEILLANT_BROKER_CONFIRMED = 'CHANGE_SURVEILLANT_BROKER_CONFIRMED',
  CHANGE_SURVEILLANT_BROKER_REJECTED = 'CHANGE_SURVEILLANT_BROKER_REJECTED',
}
